<?php

declare(strict_types=1);

namespace Tjovaisas\Bundle\DelayedEventBundle\Tests\Functional;

use Doctrine\ORM\EntityManagerInterface;
use PHPUnit\Framework\MockObject\MockObject;
use Symfony\Contracts\EventDispatcher\EventDispatcherInterface;
use Tjovaisas\Bundle\DelayedEventBundle\Tests\Functional\Fixtures\Events;
use Tjovaisas\Bundle\DelayedEventBundle\Tests\Functional\Fixtures\Entity\Entity;
use Tjovaisas\Bundle\DelayedEventBundle\Tests\Functional\Fixtures\Event\SomeEvent;
use Tjovaisas\Bundle\DelayedEventBundle\Tests\Functional\Fixtures\Listener\SomeEventListener;
use Tjovaisas\Bundle\DelayedEventBundle\Tests\Functional\Fixtures\Listener\SomeOtherEventListener;

class FunctionalEventsTest extends FunctionalTestCase
{
    /**
     * @var MockObject|SomeEventListener
     */
    private $someEventListenerMock;

    /**
     * @var MockObject|SomeOtherEventListener
     */
    private $someOtherEventListenerMock;

    /**
     * @var EventDispatcherInterface
     */
    private $eventDispatcher;

    /**
     * @var EntityManagerInterface
     */
    private $entityManager;

    protected function setUp(): void
    {
        $container = $this->setUpContainer();

        $this->setUpDatabase();

        $this->eventDispatcher = $container->get('event_dispatcher');
        $this->entityManager = $container->get('doctrine.orm.entity_manager');
        $this->someEventListenerMock = $this->createMock(SomeEventListener::class);
        $this->someOtherEventListenerMock = $this->createMock(SomeOtherEventListener::class);

        $container->set('some_event_listener', $this->someEventListenerMock);
        $container->set('some_other_event_listener', $this->someOtherEventListenerMock);
    }

    public function testListenerBeenTriggeredAfterFlushingWithAutoGeneratedDataAppearingInEntity(): void
    {
        $entity = new Entity();

        $this->entityManager->persist($entity);

        $this->eventDispatcher->dispatch(new SomeEvent($entity), Events::ON_EVENT);

        $this->someEventListenerMock
            ->expects(static::once())
            ->method('onEvent')
            ->willReturnCallback(function (SomeEvent $someEvent): void {
                $this->assertSame(1, $someEvent->getEntity()->getId());
            })
        ;

        $this->entityManager->flush();
    }

    public function testListenerHasNotBeenTriggeredWithoutAFlush(): void
    {
        $entity = new Entity();

        $this->entityManager->persist($entity);

        $this->eventDispatcher->dispatch(new SomeEvent($entity), Events::ON_EVENT);

        $this->someEventListenerMock
            ->expects(static::never())
            ->method('onEvent')
        ;
    }

    public function testListenersBeenTriggeredInACorrectOrder(): void
    {
        $entity = new Entity();

        $this->entityManager->persist($entity);

        $this->eventDispatcher->dispatch(new SomeEvent($entity), Events::ON_EVENT);

        $isTriggered = false;
        $this->someEventListenerMock
            ->expects(static::once())
            ->method('onEvent')
            ->willReturnCallback(function () use (&$isTriggered): void {
                $this->assertTrue($isTriggered);
            })
        ;

        $this->someOtherEventListenerMock
            ->expects(static::once())
            ->method('__invoke')
            ->willReturnCallback(function () use (&$isTriggered): void {
                $isTriggered = true;
            })
        ;

        $this->entityManager->flush();
    }

    public function testStopPropagationIfListenerInstructsToDoSo(): void
    {
        $entity = new Entity();

        $this->entityManager->persist($entity);

        $this->eventDispatcher->dispatch(new SomeEvent($entity), Events::ON_EVENT);

        $this->someOtherEventListenerMock
            ->expects(static::once())
            ->method('__invoke')
            ->willReturnCallback(function (SomeEvent $someEvent): void {
                $someEvent->stopPropagation();
            })
        ;

        $this->someEventListenerMock
            ->expects(static::never())
            ->method('onEvent')
        ;

        $this->entityManager->flush();
    }
}
